### ISSUE TITLE
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) 

### ISSUE THREAD

**Issue by fabotao** [KrishnaswamyLab/Multiscale_PHATE#14]
>>> tree = mp_op.build_tree()
Calculating base visualization...
Calculated base visualization in 0.01 seconds.
Calculating tree...
Calculated tree in 0.06 seconds.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/Home/fabotao/software/ENTER/envs/MultiPhate/lib/python3.11/site-packages/multiscale_phate/multiscale_phate.py", line 261, in build_tree
    return visualize.build_condensation_tree(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/Home/fabotao/software/ENTER/envs/MultiPhate/lib/python3.11/site-packages/multiscale_phate/visualize.py", line 144, in build_condensation_tree
    tree_phate = Ps[l] @ tree_phate_1
                 ~~~~~~^~~~~~~~~~~~~~
ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 77566 is different from 77565)

**Comment by fabotao** [comment]
Anyone who meets with this problem can change the random seed in "mp.Multiscale_PHATE(random_state=XXX)", more trials will work
